// Local Host
### Get all activity logs
GET http://localhost:3000/activitylogs

### Get activity log by ID
GET http://localhost:3000/activitylogs/67903d741666c20fb2ccf443

### POST - Create activity log
POST http://localhost:3000/activitylogs HTTP/1.1
content-type: application/json

{
    "action": "User logged in",
    "userId": "679018f6be2c5a72e7e3e87b",
    "timestamp": "2025-02-02T12:00:00.000Z"
}

### PUT - Update activity log
PUT http://localhost:3000/activitylogs/67903d741666c20fb2ccf443 HTTP/1.1
content-type: application/json

{
    "action": "User updated profile",
    "userId": "679018f6be2c5a72e7e3e87b",
    "timestamp": "2025-02-02T12:30:00.000Z"
}

### DELETE activity log
DELETE http://localhost:3000/activitylogs/67903d741666c20fb2ccf443 HTTP/1.1