// Local Host
### Get all activity logs
GET https://project3-cse-341.onrender.com/activitylogs

### Get activity log by ID
GET https://project3-cse-341.onrender.com/activitylogs/63d5ea08f9d5b5bc12f3b0e1

### POST - Create activity log
POST https://project3-cse-341.onrender.com/activitylogs HTTP/1.1
content-type: application/json

{
   
    "userId": "johnh",
    "action": "created task romero",
    "details": "Created 'Complete project report'.",
    "target": "task123",
    "timestamp": 1674979200,
    "ipAddress": "192.168.1.1",
    "status": "success",
    "location": "New York"
}  

### PUT - Update activity log
PUT https://project3-cse-341.onrender.com/activitylogs/67903d741666c20fb2ccf443 HTTP/1.1
content-type: application/json

{
    "action": "User updated profile",
    "userId": "679018f6be2c5a72e7e3e87b",
    "timestamp": "2025-02-02T12:30:00.000Z"
}

### DELETE activity log
DELETE https://project3-cse-341.onrender.com/activitylogs/63d5ea08f9d5b5bc12f3b0e1 HTTP/1.1