/ Local Host
### Get all collaborations
GET https://project3-cse-341.onrender.com/Collaborations

### Get collaboration by ID
GET https://project3-cse-341.onrender.com/Collaborations/63d5e9a0f9d5b5bc12f3b0d7

### POST - Create collaboration
POST https://project3-cse-341.onrender.com/Collaborations HTTP/1.1
content-type: application/json

{
    "projectId": "679018f6be2c5a72e7e3e87b",
    "userId": "67903d741666c20fb2ccf443",
    "role": "Romero",
    "joinedAt": "2025-02-02T14:00:00.000Z"
}

### PUT - Update collaboration
PUT https://project3-cse-341.onrender.com/collaboration/67903d741666c20fb2ccf443 HTTP/1.1
content-type: application/json

{
    "role": "Admin",
    "joinedAt": "2025-02-02T15:00:00.000Z"
}

### DELETE collaboration
DELETE https://project3-cse-341.onrender.com/collaboration/63d5e9a0f9d5b5bc12f3b0d7 HTTP/1.1
